### ISSUE TITLE
请教大佬这个版本如何使用的？

### ISSUE THREAD

**Issue by lee911214** [chinatengjie/Dedicated-Seedbox-Old#1]
bash <(wget -qO- https://raw.githubusercontent.com/chinatengjie/Dedicated-Seedbox-Old/main/Install.sh)  test test1234 1800
请教下杰佬这个老版本怎么使用？按照上面的命令貌似不行 不能安装qb  是哪里出问题了？  感谢大佬及时保存老版本脚本

**Comment by chinatengjie** [comment]
现在测试一下，之前没弄好。
